from MILT_mutual_information import *

"""
This file plots mutual information .npy files generated by MILT_mutual_information.
"""

if __name__ == "__main__":
    n_qubits = 6
    n_layers = 60
    probs = [0, .1]

    overall_results = []

    for p in probs:
        mean, std = np.load(f"{n_qubits}_{p}_layeredresults.npy")
        plt.errorbar(x=range(n_layers), y=mean, yerr=std, label=str(p), linewidth=3)

    plt.legend(fontsize=12)
    plt.show()
